version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: expense-tracker
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017

  redis:
    image: redis/redis-stack
    restart: always
    container_name: redis-stack
    ports:
      - 10001:10001
      - 13333:13333
    volumes:
      - redis:/data

volumes:
  mongo:
  redis:
